#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Mpietrucha\Utility\Error\Level;

Level::set(Level::ALL ^ Level::DEPRECATED);

\Mpietrucha\Pint\Application::create()->run();
