#!/usr/bin/env php
<?php

$autoload = array_filter([
    $GLOBALS['_composer_autoload_path'] ?? '',
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../../autoload.php',
], is_file(...));

require_once end($autoload) ?: exit('Missing autoload');

\Mpietrucha\Zed\Pint\Compiler::build()->emit();
